name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # 👈 Add this line to define an environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use secrets
        run: echo "Deploying with API token ${{ secrets.HF_TOKEN }}"
